config/routes.rb
Projekt1::Application.routes.draw do

root :to => "users#signin"

resources :links
match "partners/index_draft_links" => "partners#index_draft_links"

resources :partners
match "partners/new/:id" => "partners#new"
match "partners/add_link" => "partners#add_link"

match 'users/create' => 'users#create'
match 'users/signin' => 'users#signin'
match 'users/edit' => 'users#edit'
match 'users/exit' => 'users#exit'

match 'links/new' => 'links#new'
match '/id/:id' => 'users#show'
match '/clicks/create/:id'=>'clicks#create'

end

app/models/click.rb
class Click < ActiveRecord::Base
    belongs_to :link
end

app/models/link.rb
# encoding: utf-8

class Link < ActiveRecord::Base

  belongs_to :user
  belongs_to :partner
  has_many :cliks

IPv4_PART = /\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]/
ALNUM = "ä".match(/[[:alnum:]]/) ? /[[:alnum:]]/ : /[^\W_]/

#DOMAIN = /([a-z0-9\-]+\.?)*([a-z0-9]{2,})\.[a-z]{2,}/
DOMAIN =/(com|edu|gov|int|mil|net|org|biz|arpa|info|name|pro|aero|coop|museum|eu|asia|pro|ac|ad|ae|aero|af|ag|ai|al|am|an|ao|aq|ar|arpa|as|asia|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|biz|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cat|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|com|coop|cr|cu|cv|cx|cy|cz|de|dj|dk|dm|do|dz|ec|edu|ee|eg|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gov|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|info|int|io|iq|ir|is|it|je|jm|jo|jobs|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mil|mk|ml|mm|mn|mo|mobi|mp|mq|mr|ms|mt|mu|museum|mv|mw|mx|my|mz|na|name|nc|ne|net|nf|ng|ni|nl|no|np|nr|nu|nz|om|org|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|pro|ps|pt|pw|py|qa|re|ro|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|st|su|sv|sy|sz|tc|td|tel|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|travel|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|xxx|ye|yt|za|zm|zw|рф)/

  REGEXP = %r{
    \A
    (https?://)?                                                          # http:// or https://
    ([^\s:@]+:[^\s:@]*@)?                                              # optional username:pw@
    ( ((#{ALNUM}+\.)*xn--)?#{ALNUM}{2,}([-.]#{ALNUM}+)*\.#{DOMAIN}\.? |  # domain (including Punycode/IDN)...
        (#{IPv4_PART}(\.#{IPv4_PART}){3}) )                              # or IPv4
    (:\d{1,5})?                                                        # optional port
    ([/?]\S*)?                                                         # optional /whatever or ?whatever
    \Z
  }iux

#####
#    ( ((#{ALNUM}+\.)*xn--)?#{ALNUM}+([-.]#{ALNUM}+)*\.[a-zа-я]{2,6}\.? |  # domain (including Punycode/IDN)...


#####



before_validation  {self.link.strip!}

	validates :link, :presence => true , :format => {:with => /#{REGEXP}/, :message => "Некорректный формат партнерской ссылки"}

public

def get_nonactive_links
	Link.where(:active=>false)
end

end

app/models/partner.rb
class Partner < ActiveRecord::Base

   has_many :links

end

app/models/user.rb
class User < ActiveRecord::Base

   has_many :links

end

app/controllers/application_controller.rb
require "ap"

class ApplicationController < ActionController::Base

  
  protect_from_forgery
  
  private
  
  def set_current_user
    unless session[ :user_id ]
      redirect_to :root
      false
    else
      @user ||= User.find( session[ :user_id ] )
      true      
    end
  end

end

app/controllers/clicks_controller.rb
class ClicksController < ApplicationController

  def create
 		if Link.exists?(params[:id])
   		@link=Link.find(params[:id])
   		puts @link.inspect
   		puts '@@@'
   		puts params[:id]
  		Click.create(:ip=>'100500', :link_id=>params[:id])
				redirect_to 'http://' + @link.link
  		else redirect_to :controller => :users, :action => :signin
		end

  end

end

app/controllers/links_controller.rb
# encoding: utf-8

class LinksController < ApplicationController

  before_filter :set_current_user, :only => [ :new, :create ]
  
  def index
    
    redirect_to :action=>'new'
    
  end

  def new
    #создается поле запроса, для новой ссылки
    @link = Link.new

    @active_links = @user.links.where( :active => true )
    @nonactive_links = @user.links.where( :active => false )
    
  end

  def create

    #Валидация ссылки, на правильность формата и отсутствие матерков :)
    @link=Link.new(:link=>params[:link][:link])
    if @link.valid?!=true
              @active_links=@user.links.where(:active=>true)
              @nonactive_links=@user.links.where(:active=>false)
      render :action=>:new
      return
    end

    #Ищем, есть ли уже такой партнер в базе:
    partner_id=search_partner(params[:link][:link])

    if partner_id!=nil
      flash[:notice] = "Есть такой партнер, ссылка добавлена  в открытый доступ."
      active=true
    else
      active=false
      flash[:notice] = "Спасибо, такого партнера еще нет. Ссылка станет активной, после добавления модератором."
    end

    @link = @user.links.new(
       :link=>params[:link][:link],
       :active=>active,
       :partner_id=>partner_id)


    @link.save

    redirect_to :action=>:new

  end

  def search_partner(link)

    Partner.all.each do |p|
      return p.id if (link =~ Regexp.new("#{p.regex}"))!=nil

    end

    return nil #partner_id
  end

  def destroy
    @link=Link.find(params[:id])
    @link.destroy

    redirect_to :links
  end

end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  def index
    @partners=Partner.all(:order=>'url')
  end

  def index_draft_links
		@links=Link.new
		@draft_links=@links.get_nonactive_links
  end

  def new
		@partner=Partner.new
		@draft_link=Link.find(params[:id])
  end

  def create
	@site = params[:site]
	@desc = params[:description]
	@regex = params[:regex]
	@n=0
	@links=Link.new
	#все неактивные еще линки (без партнеров)
	@draft_links=@links.get_nonactive_links

  # линки попавшие под regex
	$selected_links=[]

  #выберем линки, попадающие в веденный regex партнера
	@draft_links.each do |p|
		if (p.link =~ Regexp.new("#{@regex}"))!=nil
				then	$selected_links[@n]=p.link
					@n=@n+1

		end
	end
end

  # добавим партнера базу, и сделаем активными все линки нового партнера
  def add_link
	  @p = Partner.create(:url => params[:site], :description => params[:desc], :regex => params[:regex])

		$selected_links.each do |p|
			@l=Link.find_by_link(p)
			@l.partner_id = @p.id
			@l.active=true

			@l.save!
		end


	  redirect_to :action=>"index_draft_links"
  end

def edit
  @partner=Partner.find(params[:id])
end

def show
  @partner=Partner.find(params[:id])
end

def update
  @partner = Partner.find(params[:id])

  @partner.update_attributes(params[:partner])

  redirect_to :partners

end

def destroy
  puts @partners_links.inspect
  @l=Link.new
  @partners_links=@l.find_by_partner_id(params[:id])
  if @partners_links!=nil then
    @partners_links.each do |l|
      l.update(:active=>false, :partner_id=>nil)
    end
  end

  puts @partners_links.inspect


  @partner=Partner.find(params[:id])
#  @partner.destroy

  redirect_to :partners
end

end

app/controllers/users_controller.rb
require 'json'

#require 'yaml'

class UsersController < ApplicationController
  
  require "net/http"
  require "uri"

  def signin

    if session[ :user_id ].nil?    
      render 'signin.html.erb'
    else
      redirect_to :links
    end
    
  end

  def create
   
    @token = params[:token]
    uri = ('http://loginza.ru/api/authinfo?token=') + @token
    @result = Net::HTTP.get(URI(uri))
    
    @result = JSON::[] @result      
    @user = User.find_or_create_by_loginza( @result[ 'identity' ] )
    
    session[ :user_id ] = @user.id

    redirect_to :links
    
  end

  def exit
    
    reset_session
    redirect_to :action => :signin
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/partner_helper.rb
module PartnerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Partnerdock</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>


<%= yield %>

</body>
</html>

app/views/links/_link.html.erb
<td><%= @l.link %><%= "      ---     #{@l.partner.description if @l.partner!=nil}      ---     #{@l.partner.url if @l.partner!=nil} +++ " %></td>
<td>
<%= Click.find_all_by_link_id(@l[:id]).count %>
<%= link_to 'Del', @l, :confirm => 'Вы уверены?', :method => :delete %>

</td>

app/views/links/new.html.erb
<div>
<%= link_to "Выйти", '/users/exit' %>|
<%= link_to "Публичная страница ==>", '/id/'+ session[ :user_id ].to_s %>
<%= text_field_tag 'name', '127.0.0.1:3000/id/'+ session[ :user_id ].to_s, :disabled => true %>|
<% if @user.admin == true %>
<%= link_to "Админка", '/partners/index_draft_links' %>
<% end %>
</div>

<h2><%= "Добро пожаловать, #{@user[:name]}!"%></h2>

<div>
	<% if flash[:notice] %>
		<div class="notice">
		  <%= flash[:notice] %>
		</div>
	<% end %>
</div>

<p> Добавьте партнерскую ссылку:</p>

<%= form_for @link do |f| %>
	<% if @link.errors.any? %>
    <div id="error_explanation">
      <h2>Ошибка</h2>
      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :link %>
  </div>
	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

<br>
<div>
	<h3>Партнерские ссылки:</h3>

	<p>"партнерская ссылка  --- описание партнера  ---   сайт партнера +++ число переходов"</p>

	<% @active_links.each do |l|%>
		<table>
		<tr><% @l=l %><%= render "link"%>
		</tr>
		</table>
	<% end %>
</div>
	<br>
<div>
	<h3>Ссылки, которые хотят стать хорошими:</h3>
	<% @nonactive_links.each do |l|%>
		<table>
		<tr><% @l=l %>	<%= render "link"%> </tr>
		</table>
	<% end %>
</div>

app/views/partners/_link.html.erb
<td><b><%= @l.link %></b></td>
<td>---<%= @l.user_id %>---</td>
<td><%= @l.created_at %></td>
<td><%= link_to "Добавить", '/partners/new/'+@l.id.to_s %></td>

app/views/partners/create.html.erb
<h1>Ссылок, подподающих под данное правило: <%= @n %></h1>

<div>
	<% $selected_links.each do |l|%>
			<%= l %><br>
		<% end %>
</div>

<%= form_tag('/partners/add_link') do %>
<%= hidden_field_tag 'site', @site %>
<%= hidden_field_tag 'desc', @desc %>
<%= hidden_field_tag 'regex', @regex %>
<%= submit_tag "Применить изменения" %>
<% end %>

<%= link_to "Назад", url_for(:back) %>

app/views/partners/edit.html.erb
<h3><p>Редактирование партнера :<%= @partner.id %></h3>

<%= form_for(@partner) do |f| %>
  <div class="field">
    <%= f.label "Url" %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label "description" %><br />
    <%= f.text_area :description, :size=>"25x3" %>
  </div>
  <div class="field">
    <%= f.label "regex" %><br />
    <%= f.text_field :regex , :disabled => 'disabled' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', partners_path %>

app/views/partners/index.html.erb
<%= link_to 'Назад к ссылкам', :controller=>'links' %>|
<%= link_to 'Добавление партнеров', :controller=>'partners', :action=>'index_draft_links' %>
<h1>Редактировать партнеров:<br>
<h3>url партнера--описание--regex</h3><br>

<%  @i=0  %>

<table>
  <% for p in @partners  %>
  <% @i=@i+1 %>
  <tr>
    <td>
    <%= "#{@i}. #{p.url} -- #{p.description} -- #{p.regex}" %>

    <%= link_to 'Edit', edit_partner_path(p) %>
    <%= link_to 'Del', p, :confirm => 'Вы уверены?', :method => :delete %>
    </td>
  </tr>
<%end%>
</table>

app/views/partners/index_draft_links.html.erb
<%= link_to "Назад  к ссылкам", '/links/new' %>
|<%= link_to "Редактировать партнеров", :controller=>'partners' %>

<h1>Добавление партнеров :</h1>
<p>партнерская ссылка  --- user id  ---   время добавления</p>

<div>
	<% @draft_links.each do |l|%>
		<table>
		<tr><% @l=l %><%= render "link"%></tr>
		</table>
	<% end %>
</div>

app/views/partners/new.html.erb
<%= link_to "Назад", :back %>
<h3>Назначить партнера для ссылки: <b><br></h3>
<h4><%= @draft_link.link %></h4>

<%= form_tag ('/partners') do %>
<%= label_tag "Url партнера:"%><br>
<%= text_field_tag 'site', @draft_link.link %><br>
<%= label_tag "Description:"%><br>
<%= text_area_tag 'description', @draft_link.link %><br>
<%= label_tag "regex:"%><br>
<%= text_field_tag 'regex', @draft_link.link %><br>
<%= submit_tag "Проверить regex"%>
<% end %>

app/views/partners/show.html.erb
<p>Партнер:</p>

<p>
  <b>Url:</b>
  <%= @partner.url %>
</p>

<p>
  <b>Description:</b>
  <%= @micropost.user_id %>
</p>

<p>
  <b>regex:</b>
  <%= @micropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/users/_link.html.erb
<td><%= link_to @l.partner.url, :controller=>'clicks', :action=>'create', :id=>@l %></td>
<td><%= @l.partner.description %></td>

app/views/users/edit.html.erb
<br>
<h2> И как же вас зовут?</h2>
<%= form_tag('/users/edit') %>
<%= text_field_tag 'name' %>
<%= submit_tag "Update" %>

app/views/users/show.html.erb
<head>
<script type="text/javascript" src="http://userapi.com/js/api/openapi.js?34"></script>
<script type="text/javascript">
  VK.init({apiId: 2447247, onlyWidgets: true});
</script>
</head>

<br>
<h2> Ссылки от <%= @user[:name] %>.</h2>
<br>
<div>
	<% @active_links.each do |l|%>
		<table>
		<tr><% @l=l %><%= render "link"%></tr>
		</table>
	<% end %>
</div>


	<br>


<div id="vk_like"></div>
<script type="text/javascript">
VK.Widgets.Like("vk_like", {type: "10"});
</script>

		<br>
	<script src="http://connect.facebook.net/ru_RU/all.js#xfbml=1"></script>
<fb:like></fb:like>
	<br>

<div>
<script src="http://odnaknopka.ru/ok3.js" type="text/javascript"></script>
</div>

app/views/users/signin.html.erb
<script src="http://loginza.ru/js/widget.js" type="text/javascript"></script>

<iframe src="http://loginza.ru/api/widget?overlay=loginza&token_url=http://127.0.0.1:3000/users/create&providers_set=vkontakte,facebook,twitter&lang=ru"
style="width:359px;height:300px;" scrolling="no" frameborder="no"></iframe>